import Head from 'next/head'
import Link from 'next/link';
import styled from 'styled-components'
import useMediaQuery from '@mui/material/useMediaQuery';
import { COLORS } from '@/constants';
import Frower from '@/components/Frower';
import HoverText from '@/components/Hovertext';

export default function Home() {
  const isMobile = useMediaQuery('(max-width:450px)')

  return (
    <>
      <Head>
        <title>Joronoa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" href="/public/hua.png" sizes="any" />
      </Head>
      <main style={{
        display:'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center'
      }}>
        <HomeContent className='section'>
          <Header>
            <Frower width={150} position='relative' />
            <Title isMobile={isMobile}>
              i am 
              <Name>
                <HoverText hoverText=' joronoa' unhoverText=' joey hua' />
              </Name>
            </Title>
          </Header>
          <Career isMobile={isMobile}>
            <Link href='/code_projects'>
              <HoverText hoverText='/code_projects' unhoverText='programmer' />
            </Link>
          </Career>
          <Passion isMobile={isMobile}>
            <Link href='/music_blog'>
              <HoverText hoverText='/music_blog' unhoverText='musical artist' />
            </Link>
          </Passion>
          <Heritage isMobile={isMobile}>
            <HoverText hoverText='中国人' unhoverText='chinese' />
          </Heritage>
          {/* <Heritage isMobile={isMobile}>GEN-Z</Heritage> */}
          {/* <Identity>follower of Christ</Identity> */}
          {/* <Hobby isMobile={isMobile}>food lover</Hobby>
          <Hobby isMobile={isMobile}>hooper</Hobby> */}
        </HomeContent>
      </main>
    </>
  )
}

const HomeContent = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  width: 100vw;
`
const Header = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  margin-bottom: 15px;
`
const Title = styled.h1<{ isMobile: boolean }>`
  font-size: ${props => props.isMobile ? '40px' : '50px'};
  margin-top: 15px;
`
const Name = styled.span`
  font-weight: bold;
  color: whitesmoke;
`

const MeNoun = styled.p<{ isMobile: boolean }>`
  font-size: ${props => props.isMobile ? '20px' : '25px'};
  margin-top: 10px;
`
const Career = styled(MeNoun)`
  color: ${COLORS.limeGreen};
`
const Passion = styled(MeNoun)`
  color: ${COLORS.lightYellow};
`
const Heritage = styled(MeNoun)`
  color: ${COLORS.scarlett};
`
const HumanRole = styled(MeNoun)`
  color: #52C5FF;
`
const Identity = styled(MeNoun)`
  color: #4046FF;
`

