import Head from 'next/head'
import Pics from '@/components/Pics'
import { useState } from 'react'
import styled from 'styled-components'
import useMediaQuery from '@mui/material/useMediaQuery';
import { COLORS } from '@/constants';

export default function Home() {
  const [nameHovered, setNameHovered] = useState(false)
  const [raceHovered, setRaceHovered] = useState(false)
  // const [zodiacHovered, setZodiacHovered] = useState(false)
  const isMobile = useMediaQuery('(max-width:450px)')

  return (
    <>
      <Head>
        <title>Joronoa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" href="/public/hua.png" sizes="any" />
      </Head>
      <main style={{
        display:'flex',
        alignItems: 'center',
      }}>
        <div className='section'>
          <Pics />
          <Title onMouseEnter={() => setNameHovered(true)} onMouseLeave={() => setNameHovered(false)} isMobile={isMobile}>
            i am <Name>{!nameHovered ? <HoverText>joey hua</HoverText> : <UnHoverText>joronoa</UnHoverText>}</Name>
          </Title>
          <Career isMobile={isMobile}>programmer</Career>
          <Career isMobile={isMobile}>
            <a href='https://open.spotify.com/artist/1zEBlYdwmgdTZAOHE753V2?si=T84NnR93TMOao-aTDgs6ng' target='_blank'>musical artist</a>
          </Career>
          <Heritage onMouseEnter={() => setRaceHovered(true)} onMouseLeave={() => setRaceHovered(false)} isMobile={isMobile}>
            {raceHovered ? <HoverText>中国人</HoverText> : <UnHoverText>chinese</UnHoverText>}
          </Heritage>
          {/* <Heritage>2nd-gen immigrant</Heritage> */}
          <Heritage isMobile={isMobile}>GEN-Z</Heritage>
          {/* <Heritage> */}
            {/* year of the dragon */}
            {/* year of the <span onMouseEnter={() => setZodiacHovered(true)} onMouseLeave={() => setZodiacHovered(false)}>{zodiacHovered ? <HoverText>龙</HoverText> : <UnHoverText>dragon</UnHoverText>}</span> */}
          {/* </Heritage> */}
          {/* <HumanRole>friend</HumanRole>
          <HumanRole>son</HumanRole>
          <HumanRole>brother</HumanRole> */}
          {/* <Identity>follower of Christ</Identity> */}
          <Hobby isMobile={isMobile}>food lover</Hobby>
          <Hobby isMobile={isMobile}>hooper</Hobby>
        </div>
      </main>
    </>
  )
}

const Title = styled.h1<{ isMobile: boolean }>`
  font-size: ${props => props.isMobile ? '40px' : '50px'};
`
const Name = styled.span`
  font-weight: bold;
  color: whitesmoke;
`

const MeNoun = styled.p<{ isMobile: boolean }>`
  font-size: ${props => props.isMobile ? '20px' : '25px'};
`
const Career = styled(MeNoun)`
  color: ${COLORS.limeGreen};
`
const Heritage = styled(MeNoun)`
  color: ${COLORS.scarlett};
`
const HumanRole = styled(MeNoun)`
  color: #52C5FF;
`
const Identity = styled(MeNoun)`
  color: #4046FF;
`
const Hobby = styled(MeNoun)`
  color: ${COLORS.lightYellow};
`

const HoverText = styled.span`
  animation: fadeIn 0.3s ease-in-out;
`
const UnHoverText = styled.span`
  animation: fadeIn 0.3s ease-in-out;
`

