import Head from 'next/head'
import Pics from '@/components/Pics'
import Link from 'next/link'
import Sidebar from '@/components/Sidebar'
import { useState } from 'react'
import styled from 'styled-components'

export default function Home() {
  const [race, setRace] = useState('chinese')

  return (
    <>
      <Head>
        <title>Joronoa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='section'>
          <Career>musical artist</Career>
          <Career>programmer</Career>
          <Race></Race>
          <Heritage>2nd-gen immigrant</Heritage>
          <Heritage>gen-z</Heritage>
          <Heritage>year of the dragon</Heritage>
          <HumanRole>friend</HumanRole>
          <HumanRole>son</HumanRole>
          <HumanRole>brother</HumanRole>
          {/* <Identity>follower of Christ</Identity> */}
          <Hobby>food lover</Hobby>
          <Hobby>hooper</Hobby>
        </div>
      </main>
    </>
  )
}

const Career = styled.h1 `
  color: #66FF8A
`
const Heritage = styled.h1`
  color: #FF6242
`
const Race = styled(Heritage)`
  &:before {
    content: 'chinese'
  }
  &:hover:before {
    content: '中国人'
  }
`
const HumanRole = styled.h1`
  color: #52C5FF
`

const Identity = styled.h1`
  color: #4046FF
`

const Hobby = styled.h1`
  color: #FFF79C
`

