import Head from 'next/head'
import Pics from '@/components/Pics'
import { useState } from 'react'
import styled from 'styled-components'

export default function Home() {
  const [nameHovered, setNameHovered] = useState(false)
  const [raceHovered, setRaceHovered] = useState(false)
  const [zodiacHovered, setZodiacHovered] = useState(false)

  return (
    <>
      <Head>
        <title>Joronoa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" href="/public/hua.png" sizes="any" />
      </Head>
      <main style={{
        display:'flex',
        alignItems: 'center',
      }}>
        <div className='section'>
          <Title onMouseEnter={() => setNameHovered(true)} onMouseLeave={() => setNameHovered(false)}>
            i am <Name>{nameHovered ? <HoverText>joey hua</HoverText> : <UnHoverText>joronoa</UnHoverText>}</Name>
          </Title>
          <Career><a href='https://open.spotify.com/artist/1zEBlYdwmgdTZAOHE753V2?si=T84NnR93TMOao-aTDgs6ng' target='_blank'>musical artist</a></Career>
          <Career>programmer</Career>
          <Heritage onMouseEnter={() => setRaceHovered(true)} onMouseLeave={() => setRaceHovered(false)}>
            {raceHovered ? <HoverText>中国人</HoverText> : <UnHoverText>chinese</UnHoverText>}
          </Heritage>
          <Heritage>2nd-gen immigrant</Heritage>
          <Heritage>GEN-Z</Heritage>
          <Heritage>
            year of the dragon
            {/* year of the <span onMouseEnter={() => setZodiacHovered(true)} onMouseLeave={() => setZodiacHovered(false)}>{zodiacHovered ? <HoverText>龙</HoverText> : <UnHoverText>dragon</UnHoverText>}</span> */}
          </Heritage>
          <HumanRole>friend</HumanRole>
          <HumanRole>son</HumanRole>
          <HumanRole>brother</HumanRole>
          {/* <Identity>follower of Christ</Identity> */}
          <Hobby>food lover</Hobby>
          <Hobby>hooper</Hobby>
        </div>
        <Pics />
      </main>
    </>
  )
}

const Title = styled.h1`
  font-size: 50px;
`
const Name = styled.span`
  font-weight: bold;
`
const Career = styled.h1`
  color: #66FF8A;
`
const Heritage = styled.h1`
  color: #FF6242;
`
const HumanRole = styled.h1`
  color: #52C5FF;
`
const Identity = styled.h1`
  color: #4046FF;
`
const Hobby = styled.h1`
  color: #FFF79C;
`

const HoverText = styled.span`
  animation: fadeIn 0.3s ease-in-out;
`
const UnHoverText = styled.span`
  animation: fadeIn 0.3s ease-in-out;
`

